# Generated by Django 3.0.6 on 2020-05-23 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200523_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 23, 14, 2, 40, 231780)),
        ),
    ]
